name: SailfishConnect build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  RELEASE: 3.3.0.14

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/cache@v2
      with:
        path: .venv-conan-*
        key: venv-cache3

    - name: Check style
      run: python3 scripts/bad-style.py bad-style.xml

    - name: Build armv7hl
      run: docker run --rm --privileged -v $PWD:/home/nemo/project coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
            cd /home/nemo/project && mb2 -X -t SailfishOS-$RELEASE-armv7hl build -d -j 2"

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: sailfishconnect-rpms
        path: RPMS

    - name: Check
      run: docker run --rm --privileged -v $PWD:/home/nemo/project coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
            cd /home/nemo/project && mb2 -X -t SailfishOS-3.1.0.12-armv7hl make check"