name: SailfishConnect build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  RELEASE: 3.3.0.14

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/cache@v2
      with:
        path: .venv-conan-*
        key: venv-cache3

    - name: Check style
      run: python3 scripts/bad-style.py bad-style.xml

    - name: Build armv7hl RPMS
      uses: R1tschY/sailfish-sdk-action@v1
      with:
        arch: 'armv7hl'
        release: '3.3.0.16'
        fix-version: false
        enable-debug: true
        #check: true

    - name: Build i486 RPMS
      uses: R1tschY/sailfish-sdk-action@v1
      with:
        arch: 'i486'
        release: '3.3.0.16'
        fix-version: false
        enable-debug: true
        #check: true

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: sailfishconnect-rpms
        path: RPMS